//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Post_Install_Wizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Post_Install_Wizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\mdt\deploymentshare$.
        /// </summary>
        internal static string DeploymentshareLocation {
            get {
                return ResourceManager.GetString("DeploymentshareLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\server\LiteTouch\LiteTouch.exe.
        /// </summary>
        internal static string LTExeLocation {
            get {
                return ResourceManager.GetString("LTExeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\mdt\deploymentshare$\Scripts\LiteTouch.vbs.
        /// </summary>
        internal static string LTScriptLocation {
            get {
                return ResourceManager.GetString("LTScriptLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\mdt.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\mdt\wsus.
        /// </summary>
        internal static string WSUSDir {
            get {
                return ResourceManager.GetString("WSUSDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\mdt\wsus\updateinstaller.exe.
        /// </summary>
        internal static string WSUSExe {
            get {
                return ResourceManager.GetString("WSUSExe", resourceCulture);
            }
        }
    }
}
